### ISSUE TITLE
Aufbau der Grobstruktur

### ISSUE THREAD

**Issue by Slaergh** [Slaergh/Mathbase#2]
- [x] Videoplayer (Über Standardplayer)
- [x] PDF / Document - Viewer (Über Standardviewer)
- [x] Bilderanzeige 
- [x] Feld für einfache Texteingaben und -anzeige
---
- [x] Speicheroption für alle Dateien (Um sie selbst verwenden zu können)
- [x] Suchfunktion
- [x] Adminfunktion: Hinzufügen/Löschen/Ändern von Dateistruktur und einzelnen Dateien; passwortgeschützter Zugang
---
**Andere Kriterien:**
- [x] Corporate Design einhalten (zum Glück haben wir keins ^_^)

**Comment by lumpenputzer** [comment]
* Videoplayer
* PDF / Document - Viewer
* Bilderanzeige
* Feld für einfache Texteingaben und -anzeige
---
* Speicheroption für alle Dateien (Um sie selbst verwenden zu können)
* Suchfunktion
* Adminfunktion: Hinzufügen/Löschen/Ändern von Dateistruktur und einzelnen Dateien; passwortgeschützter Zugang
---
**Andere Kriterien:**
* Corporate Design einhalten

**Comment by lumpenputzer** [comment]
Grobstruktur ist da, es fehlt Hinzufügen/Löschen von Inhalten und eine kleine Aufhübschung. Dafür gibt es aber ein anderes Issue!
