### ISSUE TITLE
Konsequente Sortiertheit

### ISSUE THREAD

**Issue by Slaergh** [Slaergh/Mathbase#20]
Alle Knoten innerhalb einer Ebene sollen jederzeit sowohl in der XML-Datei als auch im GUI-Baum **alphabetisch sortiert** sein. Dies muss bei Einfüge- und Verschiebeoperationen beachtet werden!

**Comment by lumpenputzer** [comment]
Dat wird sehr interessant ...

**Comment by Slaergh** [comment]
@lumpenputzer Zur Sicherheit sortier ich im GUI-Baum einfach nochmal nach ^^

**Comment by lumpenputzer** [comment]
Wäre vermutlich besser, da wir sonst beim Einfügen immer den kompletten Child-Tree auslesen müssen ... Andererseits wäre das mit insertChild() auch schnell erledigt ...
