### ISSUE TITLE
Formatierung der XML-Datei

### ISSUE THREAD

**Issue by Slaergh** [Slaergh/Mathbase#21]
Bisher ist es so, dass bei XML-Manipulationen die XML-Formatierung stark in Mitleidenschaft gezogen wird. Dies sollte angepasst werden, sodass alle Einrückungen, Zeilenumbrüche etc. hübsch bleiben 🌮

**Comment by lumpenputzer** [comment]
da bin ich mir nicht sicher ob wir da viel machen können ... Sieht ja schon mal besser aus als ganz am Anfang :>

**Comment by lumpenputzer** [comment]
Meintest ja es passt jez, indent² :+1:
