### ISSUE TITLE
Korrektes Exception-Handling

### ISSUE THREAD

**Issue by Slaergh** [Slaergh/Mathbase#25]
* bedingungslos try-with-resources benutzen: http://openbook.rheinwerk-verlag.de/javainsel/07_006.html#u7.6
* keine unchecked exceptions wie die IllegalArgumentException schmeißen: http://openbook.rheinwerk-verlag.de/javainsel9/javainsel_06_003.htm#mj496a3283e49d36b5db87d04fd0c0d202
* nicht übermäßig Ausnahmen werfen

**Comment by lumpenputzer** [comment]
Soweit so funktionierend. Kommt in Aufräumarbeiten rein ...
