### ISSUE TITLE
Synchronisation von Manipulationen

### ISSUE THREAD

**Issue by Slaergh** [Slaergh/Mathbase#27]
Wenn in der XML-Datei was hinzugefügt, geändert, gelöscht etc. wird, **muss** dies exakt so auf dem Dateisystem abgebildet werden und andersherum! Wenn z.B. ein Fehler beim Erstellen des neuen Ordners auftritt, muss auch der neue XML Node wieder weg, wenn die Umbenennung eines Ordners gelingt, aber des Knotens nicht, muss der Ordner wieder zurück umbenannt werden!

**Comment by lumpenputzer** [comment]
Jut jut, betrifft dann im Prinzip move, add, delete, rename, wird gemacht

**Comment by lumpenputzer** [comment]
Sodala. Ewiges zurückgeändere des Documents ist gewollt, damit dass Programm noch verwendbar ist, auch wenn die XML-Datei lost ist. Andernfalls könnte man auch immer einen Reload erzwingen ...
