### ISSUE TITLE
Aufräumarbeiten

### ISSUE THREAD

**Issue by Slaergh** [Slaergh/Mathbase#28]
- [x] In TopicTreeController getNode() konsequent einsetzen (aber wirklich. Wird langsam echt hässlich)

- [x] NodeMissingException rausschmeißen (oder als RunTimeException umschreiben)

- [x] TitleCollisionException rausschmeißen, indem die addNode Methode einen bool zurückgibt _(? Inhalte werden ja über Pfad identifiziert, daher wird die Ausnahme kaum genutzt)_ oder der Aufrufende vorher doesExist benutzt, des weiteren muss bei moveNode davon ausgegangen werden, dass keine Illegalen Parameter verwendet werden ...

- [x] Verbessertes Exceptionhandling

**Comment by lumpenputzer** [comment]
ja, meistens wird nur ein Knoten gefordert ... des kann man aber leicht umändern :D

**Comment by Slaergh** [comment]
Na dann...
