### ISSUE TITLE
Überarbeitung der Existenzprüfung

### ISSUE THREAD

**Issue by Slaergh** [Slaergh/Mathbase#29]
Wenn der Knoten "Nudelsaft" existiert und der User "nudelsaft" hinzufügen will, checkt die Methode _doesExist(String title)_ das nicht!! Die Titel müssen immer auf der normalisierten Ebene verglichen werden!

**Comment by lumpenputzer** [comment]
Ist doch schon geändert. Gestern schon!

**Comment by Slaergh** [comment]
@lumpenputzer Deine XPathExpression scheint von vornherein nur die Knoten, deren Titel exakt mit dem gegebenen übereinstimmt, zurückzugeben...

**Comment by lumpenputzer** [comment]
Dann müssen wir den Pfad doch wieder mit abspeichern, anders geht das nicht.

**Comment by lumpenputzer** [comment]
Es sei denn man lässt alle Knoten raus. Dann dauerts halt. Allerdings benötigt man die Methode theoretisch nur zum einfügen, wenn wir davon ausgehen dass kein teil des Programms nach einem nicht vorhandenen Knoten sucht, da eigentlich immer irgendeine Liste der Titel vorhanden sein müsste. Muss man dann natürlich drauf achten, erleichtert aber einiges ...

**Comment by lumpenputzer** [comment]
liest alle Knoten aus*

**Comment by Slaergh** [comment]
@lumpenputzer Du könntest ja auch die Methode ohne XPath machen und einfach rekursiv über des `Document`-Objekt, welches ja so oder so schon die ganze Zeit geladen vorliegt, laufen.

**Comment by lumpenputzer** [comment]
Geht auch. Sollen wir trotzdem festlegen, dass außer in dieser Methode nur nach vorhandenen Titeln gesucht werden soll? Dann sparen wir uns Haufen exceptions ...

**Comment by Slaergh** [comment]
@lumpenputzer Natürlich. So ist es ja gedacht! Die GUI prüft auf Existenz und gibt den anderen Methoden im `TopicTreeController` nur vorhandene Titel

**Comment by Slaergh** [comment]
Mir is eh aufgefallen, dass wir unnötigerweise mehrmals solche checks durchführen und immer iwelche Ausnahmen schmeißen. Wir müssen uns mal zamhocken und klar definieren, an welchen Stellen was zu erwarten ist

**Comment by lumpenputzer** [comment]
Die Ausnahmen fliegen jetzt dann zur Hälfte raus, eben wegen der Vereinbarung.

**Comment by lumpenputzer** [comment]
Allerdings mach ich nachher erstmal schnell die beiden fehlenden Content-Funktionen und die doesExist, damit dass Programm grundlegend funktioniert
