### ISSUE TITLE
"About"-Fenster

### ISSUE THREAD

**Issue by lumpenputzer** [Slaergh/Mathbase#32]
Es sollte eine dieses Programm erklärende PDF-Datei geben. Auf diese sollte dann auch in einem "About"-Fenster verwiesen werden. Außerdem sollten dort Lizenz-Hinweise stehen!

**Comment by lumpenputzer** [comment]
Bitte nochmal durchlesen und auf Tipp-, bzw Schreibfehler achten. Bin zu müde dafür ...

**Comment by twillfade** [comment]
JUHU 🎉  @Nelorth
