### ISSUE TITLE
Inhaltskacheln ausbauen

### ISSUE THREAD

**Issue by Slaergh** [Slaergh/Mathbase#35]
Es sollten grundlegende Informationen wie Dateiname, Größe etc. angezeigt werden; außerdem muss irgendein Hinweis auf die Anklickbarkeit der Inhalte existieren.

**Comment by lumpenputzer** [comment]
Hinweis auf Anklickbarkeit ist im Help-Fenster ....
Dateiname ist unsinnig, ist ja immer sowas wie image1.png ...
Größe kann man machen, ist aber auch irgendwie unnötig ...
Dateityp wär vlt ganz interessant.

**Comment by lumpenputzer** [comment]
Also, was davon soll's sein? Ich denk es pascht ^^
