### ISSUE TITLE
Content Viewer

### ISSUE THREAD

**Issue by lumpenputzer** [Slaergh/Mathbase#4]
- [x] Anzeigender einzelnen Dateien mit Vorschau
- [x] Anstelle von PlainLinks werden tolle StandarTbildchen gezeigt
- [x] Hinzufügen von Inhalten funktioniert
- [x] Inhalte können gelöscht werden
- [x] Bei Doppelklick auf Dateien werden diese mit Standardprogramm geöffnet
- [x] Dateien können abgespeichert werden
- [x] ~~Beschreibungen haben Sonderstellung~~
- [x] Dateien können Titel gegeben werden

**Comment by Slaergh** [comment]
- Vorschau ist, abgesehen von Bildern, aufwändig und unnötig
- Titel kommen in das XML-File
