### ISSUE TITLE
Themenbaumkonstruktionsroutine

### ISSUE THREAD

**Issue by Slaergh** [Slaergh/Mathbase#7]
Wir brauchen eine Methode, die aus der XML-Datei ein TreeView-Objekt für die graphische Oberfläche konstruiert. Hierfür wäre eine Hilfsmethode für die Rückgabe aller Nodes unter der XML-Wurzel angebracht.

**Comment by twillfade** [comment]
Kümmere mich ab morgen (27.12.) wieder ums Projekt, kommt dann. Sonstige benötigte Sachen dann am besten als neues Issue aufmachen! @Nelorth

**Comment by Slaergh** [comment]
Ich möchte morgen auch mal ordentlich ranklotzen, am besten speaken wir dann inteam ;)
